version: '3.8'
services:
  chatbot:
    container_name: chatbot
    restart: always
    build:
      context: ./ww-js.musicbot
    environment:
      - DISPLAY=:1
    devices:
      - /dev/dri:/dev/dri

    network_mode: "host"

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - shared-data:/usr/src/app/media
      - /usr/bin:/usr/src/app/chrome



  api:
    container_name: api
    restart: always
    build:
      context: ./ww-js.musicbot.api
    ports:
      - "5000:5000"

    volumes:
      - shared-data:/usr/src/api/media
      - /remotefiles:/usr/src/api/morris


volumes:
  shared-data:



