version: '3.8'
services:
  chatbot:
    container_name: chatbot
    restart: always
    build:
      context: ./ww-js.musicbot
    volumes:
      - shared-data:/usr/src/app/songs

  api:
    container_name: api
    restart: always
    build:
      context: ./ww-js.musicbot.api
    ports:
      - "5000:5000"

    volumes:
      - shared-data:/usr/src/api/songs

volumes:
  shared-data:


